name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Nginx_Load_Balancer:
    runs-on: ubuntu-latest

    steps:
        - name: Check out the repository 
          uses: actions/checkout@v3
        - name: Login to GitHub
          run: docker login --username ${{ secrets.GHCR_USER }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        - name: Build and Push
          run: |
            docker build nginx-load-balancer/ --tag ghcr.io/${{ secrets.GHCR_USER }}/nginx-load-balancer:latest
            docker push ghcr.io/${{ secrets.GHCR_USER }}/nginx-load-balancer:latest
  
  Red_app:
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repository 
          uses: actions/checkout@v3
        - name: Login to GitHub
          run: docker login --username ${{ secrets.GHCR_USER }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        - name: Build and Push
          run: |
            docker build red/ --tag ghcr.io/${{ secrets.GHCR_USER }}/red-app:latest
            docker push ghcr.io/${{ secrets.GHCR_USER }}/red-app:latest
  
  Yellow_app:
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repository 
          uses: actions/checkout@v3
        - name: Login to GitHub
          run: docker login --username ${{ secrets.GHCR_USER }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        - name: Build and Push
          run: |
            docker build yellow/ --tag ghcr.io/${{ secrets.GHCR_USER }}/yellow-app:latest
            docker push ghcr.io/${{ secrets.GHCR_USER }}/yellow-app:latest
  
  Green_app:
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repository 
          uses: actions/checkout@v3
        - name: Login to GitHub
          run: docker login --username ${{ secrets.GHCR_USER }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io
        - name: Build and Push
          run: |
            docker build green/ --tag ghcr.io/${{ secrets.GHCR_USER }}/geen-app:latest
            docker push ghcr.io/${{ secrets.GHCR_USER }}/geen-app:latest
