name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Check out the repository 
          uses: actions/checkout@v3

        - name: Login to GitHub
          run: docker login --u wasim-iqbal --p ${{ secrets.GHCR_TOKEN }}
      
        - name: Docker build and Push
          run: |
            docker build nginx-load-balancer/ --tag ghcr.io/wasim-iqbal/task11:latest
            docker push ghcr.io/wasim-iqbal/task11:latest
